### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by LovelyBuggies** [sysu/contact#2]
Hi, I am Nino (刘硕) 2016's bachelor, major in SE, hope to join our family, could any one send me an invitation? @yesmyc

**Comment by LovelyBuggies** [comment]
Btw, maybe I can admin this org in my leisure. Would be better if you can clarify the responsibilities on the readme.

**Comment by huangjj27** [comment]
Invitation has been sent

**Comment by yesmyc** [comment]
good job !

现在才看到，给 @huangjj27 同学的手速点个赞！

学海无涯苦作舟，后浪们要继续学术有的，学业有成，工程有用哟~！

**Comment by yesmyc** [comment]
good job ! @LovelyBuggies ！

现在才看到，给 @huangjj27 同学的手速点个赞！

学海无涯苦作舟，后浪们要继续学术有的，学业有成，工程有用哟~！
