### ISSUE TITLE
Join 请求

### ISSUE THREAD

**Issue by ffengc** [sysu/contact#3]
请求加入组织，如果平时时间允许，也可以帮忙维护org下的一些项目，谢谢🌹

**Comment by ffengc** [comment]
收到，感谢🌹

**Comment by ffengc** [comment]
好的感谢你，祝你顺利🌹

**Comment by huangjj27** [comment]
@ffengc 欢迎加入 [sysu-gitlab](https://gitlab.com/sysu-gitlab), 已向学校邮箱发送了申请。

**Comment by huangjj27** [comment]
@ffengc sysu-gitlab 已发送邀请。
